name: SonarQube Scan

on:
  push:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache de SonarQube Scanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}

      - name: Análisis de SonarQube
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: 'tu-organizacion-sonarcloud'
          token: ${{ secrets.SONAR_TOKEN }}
